// src/ui/components/NavBar.vue
<script setup lang="ts"></script>

<template>
  <header>
    <nav aria-label="Navbar">
      <ul>
        <li>
          <RouterLink to="/">Findy Alternance</RouterLink>
        </li>
      </ul>
    </nav>
  </header>
</template>

<style>
@media (min-width: 1300px) {
}

@media (min-width: 700px) and (max-width: 1300px) {
}

@media (max-width: 700px) {
}

header > nav {
  display: flex;
  flex-direction: row;
  align-items: top;
}

header > nav > ul {
}

header > nav > ul > li > a {
  text-decoration: none;
}
</style>

// src/presentation/widgets/navbar/navbar.tsx
import styles from "./navbar.module.css"

const Navbar = () => {
    return (
        <header id={styles.header}>
            <nav id={styles.navbar} aria-label="Navbar">
                <ul>
                    <li>
                        <a href="/">FINDY</a>
                    </li>
                    <li>
                        <a className={styles.normalUnderline} href="/job-offers">
                            Trouvez votre alternance
                        </a>
                    </li>
                    <li>
                        <a className={styles.normalUnderline} href="/more">
                            Media
                        </a>
                    </li>
                </ul>
            </nav>
        </header>
    )
}

export default Navbar
